"""A labelled search benchmark: AI-style clip descriptions + the queries an editor would type.

Queries deliberately avoid copying the clip text word for word, so they measure whether
search finds the *moment*, not whether the user remembered the title.
"""

CLIPS = [
    ("c01", "NAHHH", "Jumpscare / Scary", "Phasmophobia",
     "The ghost appears behind him in the hallway and he screams and throws his headset off.",
     ["jumpscare", "ghost", "scream", "headset"], [(4, "ghost appears in hallway"), (6, "screams and rips headset off")],
     ["ghost scare", "screaming at ghost", "headset flies off"]),
    ("c02", "1v5 ace", "Clutch / Highlight", "VALORANT",
     "He wins a 1v5 round with a Sheriff, getting five headshots in a row as the crowd in chat goes wild.",
     ["ace", "sheriff", "headshots", "clutch", "1v5"], [(3, "first headshot"), (15, "fifth kill, round won")],
     ["one versus five", "pistol ace", "insane clutch"]),
    ("c03", "why", "Fail", "Minecraft",
     "While building a bridge he falls into lava and loses all his diamonds.",
     ["lava", "death", "diamonds", "fall"], [(8, "falls into lava"), (10, "realises items are gone")],
     ["dies in lava", "loses everything", "lava death"]),
    ("c04", "donation reaction", "Chat / Donation Reaction", "Just Chatting",
     "A viewer donates 1000 dollars and he stands up in shock, then thanks them emotionally.",
     ["donation", "shock", "thank you", "big donation"], [(2, "donation alert"), (5, "stands up shocked")],
     ["huge donation", "reacts to 1000 dollar dono", "emotional thanks"]),
    ("c05", "keyboard smash", "Rage", "Elden Ring",
     "After dying to Malenia for the 50th time he slams his keyboard and yells at the game.",
     ["rage", "malenia", "boss", "keyboard", "yelling"], [(1, "dies to Malenia"), (3, "slams keyboard")],
     ["raging at boss", "breaks keyboard", "angry at elden ring"]),
    ("c06", "cat cameo", "Wholesome", "Just Chatting",
     "His cat jumps on the desk and walks across the keyboard, he laughs and pets it.",
     ["cat", "pet", "cute", "keyboard"], [(2, "cat jumps on desk"), (7, "pets the cat")],
     ["cat walks on keyboard", "cute pet moment", "kitty on stream"]),
    ("c07", "singing", "Music", "Just Chatting",
     "He sings along badly to a karaoke track, voice cracking on the high note, chat spams LUL.",
     ["singing", "karaoke", "voice crack"], [(10, "voice cracks on high note")],
     ["bad singing", "karaoke fail", "voice cracks"]),
    ("c08", "duo with friend", "Collab / Guest", "Fortnite",
     "Playing duos with a guest streamer, they argue about who stole the loot and then both die.",
     ["duos", "guest", "argument", "loot"], [(5, "argue over loot"), (20, "both eliminated")],
     ["arguing with teammate", "duo fight over loot"]),
    ("c09", "i'm done", "Drama / Serious", "Just Chatting",
     "He talks seriously about burnout and announces he will take a break from streaming.",
     ["burnout", "break", "announcement", "serious"], [(12, "announces break")],
     ["taking a break announcement", "mental health talk"]),
    ("c10", "outside", "IRL", "IRL",
     "Walking through Tokyo at night, a stranger recognises him and asks for a photo.",
     ["tokyo", "fan", "photo", "irl", "street"], [(30, "fan asks for photo")],
     ["recognised by fan in japan", "irl stream tokyo"]),
    ("c11", "lmaooo", "Funny", "GTA V",
     "His car flips over a ramp, lands on a police car, and he bursts out laughing.",
     ["car", "flip", "police", "laughing", "stunt"], [(3, "car flips off ramp"), (5, "lands on police car")],
     ["car stunt fail", "lands on cop car", "crying laughing"]),
    ("c12", "clip it", "Clutch / Highlight", "Counter-Strike 2",
     "He hits a no-scope AWP shot through smoke to win the match point.",
     ["awp", "noscope", "smoke", "match point"], [(6, "no-scope through smoke")],
     ["noscope through smoke", "awp flick win"]),
    ("c13", "bro", "Fail", "Rocket League",
     "He scores an own goal in overtime and the team loses the ranked match.",
     ["own goal", "overtime", "loss", "ranked"], [(9, "scores own goal")],
     ["own goal overtime", "throws the game"]),
    ("c14", "WHAT", "Jumpscare / Scary", "Five Nights at Freddy's",
     "An animatronic lunges at the camera and he falls backwards off his chair.",
     ["animatronic", "jumpscare", "falls off chair", "fnaf"], [(4, "animatronic lunges"), (5, "falls off chair")],
     ["falls out of chair scared", "fnaf scare"]),
    ("c15", "chat is this real", "Funny", "Just Chatting",
     "He reads a ridiculous chat message out loud and can't stop laughing for a full minute.",
     ["chat", "laughing", "reading chat"], [(5, "reads message"), (8, "uncontrollable laughter")],
     ["laughing fit", "can't stop laughing at chat"]),
    ("c16", "gg", "Rage", "League of Legends",
     "His teammate steals Baron and he rants at them for the rest of the game.",
     ["baron", "steal", "rant", "teammate"], [(2, "baron stolen"), (4, "starts ranting")],
     ["tilted at teammate", "baron steal rage"]),
    ("c17", "dog", "Wholesome", "Just Chatting",
     "His puppy falls asleep on his lap during stream and he whispers so as not to wake it.",
     ["dog", "puppy", "sleeping", "whisper"], [(6, "puppy asleep on lap")],
     ["sleeping puppy", "whispering on stream"]),
    ("c18", "guitar", "Music", "Music",
     "He plays a guitar solo cover of a rock song perfectly and chat claps.",
     ["guitar", "solo", "cover", "rock"], [(15, "solo starts")],
     ["guitar solo", "plays rock cover"]),
    ("c19", "speedrun wr", "Clutch / Highlight", "Super Mario 64",
     "He finishes a speedrun with a new world record time and screams in celebration.",
     ["speedrun", "world record", "celebration"], [(40, "timer stops on world record")],
     ["gets the world record", "wr celebration"]),
    ("c20", "oops", "Fail", "Just Chatting",
     "He knocks a full glass of water onto his keyboard and scrambles to save it.",
     ["water", "spill", "keyboard", "accident"], [(2, "knocks over glass")],
     ["spills drink on setup", "water on keyboard"]),
    ("c21", "raid", "Chat / Donation Reaction", "Just Chatting",
     "A huge raid of 20000 viewers arrives and he panics trying to greet everyone.",
     ["raid", "viewers", "panic", "greeting"], [(1, "raid alert")],
     ["massive raid", "gets raided"]),
    ("c22", "ghost hunt", "Jumpscare / Scary", "Lethal Company",
     "A monster grabs his friend in the dark, the friend's voice cuts out and everyone panics.",
     ["monster", "friend grabbed", "dark", "panic"], [(7, "friend grabbed")],
     ["friend gets taken by monster", "coop horror panic"]),
    ("c23", "cooking", "Fail", "Just Chatting",
     "Cooking on stream he sets off the smoke alarm burning pancakes.",
     ["cooking", "smoke alarm", "pancakes", "burnt"], [(20, "smoke alarm goes off")],
     ["burns food", "smoke alarm cooking"]),
    ("c24", "beef", "Drama / Serious", "Just Chatting",
     "He responds to accusations from another streamer and gets visibly angry.",
     ["drama", "accusations", "response", "beef"], [(30, "addresses the accusations")],
     ["responds to drama", "calls out streamer"]),
    ("c25", "dance", "Funny", "Just Chatting",
     "He does a terrible dance for a sub goal while his friend films from the side.",
     ["dance", "sub goal", "cringe"], [(4, "starts dancing")],
     ["cringe dance", "sub goal dance"]),
    ("c26", "tier 3", "Clutch / Highlight", "Apex Legends",
     "He wins the game solo after his whole squad dies, last kill with a knockdown shield.",
     ["solo win", "squad wipe", "champion"], [(25, "final kill")],
     ["solo champion", "wins alone after squad dies"]),
    ("c27", "boss finally", "Clutch / Highlight", "Elden Ring",
     "After hours of attempts he finally beats Malenia with a sliver of health left.",
     ["malenia", "boss", "victory", "low health"], [(20, "final hit on Malenia")],
     ["beats malenia", "finally wins boss fight"]),
    ("c28", "mic muted", "Funny", "VALORANT",
     "He gives a long passionate speech to his team only to realise his mic was muted.",
     ["mic muted", "speech", "teammates"], [(18, "realises mic muted")],
     ["talking while muted", "forgot to unmute"]),
    ("c29", "snake", "Jumpscare / Scary", "IRL",
     "On an outdoor stream a snake crosses the path and he jumps back screaming.",
     ["snake", "scream", "outdoors", "irl"], [(3, "snake appears")],
     ["scared of snake", "irl snake scare"]),
    ("c30", "parents", "Wholesome", "Just Chatting",
     "His mum walks in with snacks and says hello to chat.",
     ["mom", "family", "snacks", "cameo"], [(2, "mum walks in")],
     ["mom walks in", "parent cameo"]),
]

# (query, expected clip id)
QUERIES = [
    ("scared by a ghost", "c01"),
    ("screams and throws headset", "c01"),
    ("ace with a pistol", "c02"),
    ("1v5", "c02"),
    ("dies in lava", "c03"),
    ("loses his diamonds", "c03"),
    ("big donation reaction", "c04"),
    ("raging at malenia", "c05"),
    ("slams keyboard", "c05"),
    ("cat on keyboard", "c06"),
    ("voice crack singing", "c07"),
    ("argue with duo partner over loot", "c08"),
    ("burnout break announcement", "c09"),
    ("fan recognises him in tokyo", "c10"),
    ("car lands on police car", "c11"),
    ("no scope through smoke", "c12"),
    ("own goal", "c13"),
    ("falls off his chair", "c14"),
    ("can't stop laughing at a chat message", "c15"),
    ("baron steal", "c16"),
    ("puppy asleep", "c17"),
    ("guitar solo", "c18"),
    ("world record speedrun", "c19"),
    ("spills water on keyboard", "c20"),
    ("huge raid", "c21"),
    ("friend taken by monster", "c22"),
    ("smoke alarm", "c23"),
    ("burnt pancakes", "c23"),
    ("responds to accusations", "c24"),
    ("cringe dance", "c25"),
    ("wins solo after squad dies", "c26"),
    ("finally beats malenia", "c27"),
    ("mic was muted", "c28"),
    ("snake", "c29"),
    ("mom walks in", "c30"),
    ("fnaf jumpscare", "c14"),
    ("headshots", "c02"),
    ("losing ranked overtime", "c13"),
    ("dances for subs", "c25"),
    ("emotional thank you", "c04"),
    ("rocket league fail", "c13"),
    ("scary animatronic", "c14"),
    ("pets his cat", "c06"),
    ("karaoke", "c07"),
    ("recognized by a fan", "c10"),
]


def seed(add_streamer, add_clip):
    import json
    sid = add_streamer("bench")
    for i, (cid, title, cat, game, summary, tags, moments, phrases) in enumerate(CLIPS):
        analysis = {"summary": summary, "category": cat, "tags": tags, "search_phrases": phrases,
                    "moments": [{"t": t, "description": d} for t, d in moments]}
        add_clip(sid, cid, title, category=cat, game_name=game, summary=summary, tags=json.dumps(tags),
                 analysis=json.dumps(analysis), status="done", view_count=1000 - i)
    return sid

# Harder: synonyms and vague editor phrasing with little word overlap.
HARD_QUERIES = [
    ("frightened streamer yelling", "c01"),
    ("furious at the boss he can't beat", "c05"),
    ("hilarious car crash with cops", "c11"),
    ("doggo napping", "c17"),
    ("kitty cameo", "c06"),
    ("terrible singing", "c07"),
    ("someone sends a lot of money", "c04"),
    ("thousands of people join the stream", "c21"),
    ("kitchen disaster", "c23"),
    ("his mother says hi", "c30"),
    ("the moment he finally wins against malenia", "c27"),
    ("fell out of his seat in fear", "c14"),
    ("talking to team but nobody could hear him", "c28"),
    ("wholesome family moment", "c30"),
    ("serious talk about quitting", "c09"),
    ("accidentally scores for the other team", "c13"),
    ("clutch round with only a handgun", "c02"),
    ("reptile scare outside", "c29"),
    ("mad at his teammate", "c16"),
    ("record breaking run", "c19"),
]

# Held out: written after tuning, never used to tune. Guards against overfitting the thesaurus.
HELDOUT_QUERIES = [
    ("ghost behind him", "c01"),
    ("five headshots", "c02"),
    ("bridge building accident", "c03"),
    ("stands up in shock", "c04"),
    ("50th death", "c05"),
    ("laughs and pets", "c06"),
    ("chat spams LUL at his singing", "c07"),
    ("guest streamer fortnite", "c08"),
    ("walking at night in japan", "c10"),
    ("gta ramp", "c11"),
    ("awp", "c12"),
    ("coop horror game panic", "c22"),
    ("angry reply to another streamer", "c24"),
    ("apex win", "c26"),
    ("snacks", "c30"),
    ("cute pet", "c06"),
    ("outdoor irl scare", "c29"),
    ("mario", "c19"),
    ("water accident", "c20"),
    ("league of legends rant", "c16"),
]
